config/routes.rb
Rails.application.routes.draw do
  resources :paintings
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :paintings
end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.fetch(:artist, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: %i[ show edit update destroy ]
  layout -> { ApplicationLayout }

  # GET /paintings or /paintings.json
  def index
    @paintings = Painting.all
    render Paintings::IndexView.new(paintings: @paintings, artists: Artist.all)
  end

  # GET /paintings/1 or /paintings/1.json
  def show
    render Paintings::ShowView.new(
      painting: @painting
    )
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings or /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to painting_url(@painting), notice: "Painting was successfully created." }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1 or /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to painting_url(@painting), notice: "Painting was successfully updated." }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1 or /paintings/1.json
  def destroy
    @painting.destroy

    respond_to do |format|
      format.html { redirect_to paintings_url, notice: "Painting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def painting_params
      params.fetch(:painting, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
  <h1><%= artist.name %></h1>
  <% artist.paintings.each do |painting| %>
    <%= painting.title  %>
    <%= render painting %>
  <% end %>
</div>

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/_painting.html.erb
<%= painting.title %>
123

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Artists</h1>

<div id="artists">
  <% @artists.each do |artist| %>
    <%= render artist %>
    <p>
      <%= link_to artist.name, artist %>
    </p>
  <% end %>
</div>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist %>

<div>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %> |
  <%= link_to "Back to artists", artists_path %>

  <%= button_to "Destroy this artist", @artist, method: :delete %>
</div>

app/views/home/index.html.erb
welcome to my site

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtPhlex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paintings/_form.html.erb
<%= form_with(model: painting) do |form| %>
  <% if painting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
        <% painting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div id="<%= dom_id painting %>">
</div>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render "form", painting: @painting %>

<br>

<div>
  <%= link_to "Show this painting", @painting %> |
  <%= link_to "Back to paintings", paintings_path %>
</div>

app/views/paintings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Paintings</h1>

<div id="paintings">
  <% @paintings.each do |painting| %>
    <%= render painting %>
    <p>
      <%= link_to "Show this painting", painting %>
    </p>
  <% end %>
</div>

<%= link_to "New painting", new_painting_path %>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render "form", painting: @painting %>

<br>

<div>
  <%= link_to "Back to paintings", paintings_path %>
</div>

app/views/paintings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @painting %>

<div>
  <%= link_to "Edit this painting", edit_painting_path(@painting) %> |
  <%= link_to "Back to paintings", paintings_path %>

  <%= button_to "Destroy this painting", @painting, method: :delete %>
</div>